1 create file structur
GSG-CF05/FinanceApp-team12 pull request #3
Opened 2022-02-06 18:26 UTC by ferasomar2

2022-02-06 18:26 UTC, ahmedhmmad approved these changes
Cool

2022-02-06 18:32 UTC, Mai-Elhajeen approved these changes

2022-02-06 20:49 UTC, husamkamal requested changes
Link the style .css file and they are in the same folder. We do not put ./

2022-02-07 01:08 UTC, closed without merging

2022-02-07 01:10 UTC, omarkhalid1998 commented
Nice